services:
  mysql:
    image: mysql:8.0
    container_name: ticket_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  n8n:
    image: n8nio/n8n
    container_name: ticket_n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - WEBHOOK_URL=http://host.docker.internal:5678
      - GROQ_API_KEY=${GROQ_API_KEY} 
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false 
    volumes:
      - n8n_data:/home/node/.n8n
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mysql_data:
  n8n_data: